name: CI-Build-Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      Solution_Name: POELevelWatch.Core.sln
      buildConfiguration: release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Dotnet build
      run: dotnet build $env:Solution_Name -c $env:buildConfiguration
